spring:
  application:
    name: AD-HELL-CORE-SERVICE
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/advertise_system   # DB?: advertise_system
    username: ADHD
    password: ADHD
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10        # ?? ??? ??
      minimum-idle: 5              # ?? ?? ??? ?
      idle-timeout: 30000          # idle ??? ?? ??(ms)
      max-lifetime: 1800000        # ???? ?? ??(ms) - ?? 30?
      connection-timeout: 30000    # ??? ??? ??? ??? ? ?? ?? ??(ms)

  jpa:
    hibernate:
      ddl-auto: create           # create, create-drop, update, validate, none ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # ??? ?? ??

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp
    default-encoding: UTF-8
#  data:
#    redis:
#      host: localhost
#      port: 6379

logging:
  level:
    org.hibernate.SQL: debug       # SQL ?? ???
    org.hibernate.type: trace      # ??? ???? ??? ??

#security:
#  jwt:
#    issuer: adhd
#    secret: ${JWT_SECRET:dev-secret-change-me-please-32bytes-min}
#    access-ttl: PT15M     # 15?
#    refresh-ttl: P14D     # 14?

jwt:
  secret-key: Q8b83bmIq4KI2lvE+bViXYvo9SyODg1g0Q0dPyG9VNutj0GgBG8SxhWwL3oexDlWtq5uxFZs+k+NWXHYXKLjYg==
  expiration: 3600000  # 1시간
  refresh-expiration: 1209600000 # 2주

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.adhd.ad_hell.domain.*.query.mapper
server:
  port: 8088                      # ?? ??

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

image:
  image-dir: "C:/Users/Playdata/ad-hell/uploads"

ad:
  # 정적 매핑이 /uploads/** 라면 이렇게 베이스 URL을 잡아두면 편합니다.
  adfile-url: "http://localhost:${server.port}/uploads"